Feat/modal
citi-onboarding/acervusej-onepage pull request #48
Opened 2020-12-10 22:47 UTC by IgrPhillipe

**Things I've done:**

- Create the functions openModal and closeModal in the ourServices component
- Create the modal component

**How to test it:**

- First download the node modules on the client and the server. If you have already done that, then:
- Change the values on .env.
- Go to client on the terminal (cd client) and put npm run start.
- On the browser write http://localhost:3000/.
- See if the header works both in mobile and desktop view.
- Look at the code to see if it has everything that it should have.

2020-12-10 23:36 UTC, JulioBem requested changes
The image is being cutted by half because of its bad positioning inside the div.

2020-12-11 00:49 UTC, Sofiamdl requested changes
On wide screens the modal is getting a bit thin

2020-12-11 00:56 UTC, Sofiamdl approved these changes

2020-12-11 01:13 UTC, JulioBem approved these changes
Good work!

2020-12-11 01:15 UTC, merged